dependencies: \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Private/Plugins/CDVLocalStorage/CDVLocalStorage.m \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Private/Plugins/CDVLocalStorage/CDVLocalStorage.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVPlugin.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVPluginResult.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVAvailability.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVAvailabilityDeprecated.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/NSMutableArray+QueueAdditions.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVCommandDelegate.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVInvokedUrlCommand.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVWebViewEngineProtocol.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDV.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVAppDelegate.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVViewController.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVCommandQueue.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVScreenOrientationDelegate.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVWhitelist.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVTimer.h \
  /Users/behring/Developer/cordova/hello/platforms/ios/CordovaLib/Classes/Public/CDVUserAgentUtil.h
